stages:
  create-dataset:
    cmd: python scripts/create_dataset.py
    deps:
    - scripts/create_dataset.py
    outs:
    - assets/data
  data-preprocessing:
    cmd: python scripts/pre_processing.py
    deps:
    - assets/data/x_test.npy
    - assets/data/x_train.npy
    - assets/data/y_test.npy
    - assets/data/y_train.npy
    - scripts/pre_processing.py
    outs:
    - assets/features
  train-model-CNN:
    cmd: python scripts/train_model.py
    deps:
    - assets/features/x_train_features_cnn.npy
    - assets/features/y_train_labels_cnn.npy
    - scripts/train_model.py
    outs:
    - assets/models
  eval-model-CNN:
    cmd: python scripts/eval_model.py
    deps:
    - assets/features/x_test_features_cnn.npy
    - assets/features/y_test_labels_cnn.npy
    - assets/models/model.pk
    - scripts/eval_model.py
    outs:
    - assets/metrics.json
